### ISSUE TITLE
Add accordions

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets.gov-patterns#17]
<img width="1003" alt="screen shot 2016-09-30 at 5 35 46 pm" src="https://cloud.githubusercontent.com/assets/3453669/19007717/648b97a2-8734-11e6-90d4-2c74af44d254.png">

Source: https://dev.vets.gov/playbook/governance/

**Comment by bshyong** [comment]
just writing a note here for reference: `uswds.js` is breaking patternlab's javascripts so we probably will need to write our own simple js for these accordions. did some debugging and couldn't get uswds scripts to not screw with patternlabs generated build
