### ISSUE TITLE
Add Green "Apply for ..." Buttons

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets.gov-patterns#2]
<img width="300" alt="screen shot 2016-09-30 at 5 03 25 pm" src="https://cloud.githubusercontent.com/assets/3453669/19006872/e753201a-872f-11e6-956b-c3268b219c3b.png">

Source: https://www.vets.gov/healthcare/apply/

**Comment by bshyong** [comment]
Will be resolved by 4adf78105457cb4f39e4ca223d052d14c0840693; adds primary (green) button
