### ISSUE TITLE
Create Human Readable Section Names

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets.gov-patterns#23]
![screen shot 2016-10-06 at 9 42 14 am](https://cloud.githubusercontent.com/assets/3453669/19154738/c2969774-8ba9-11e6-8784-a68b2f252654.png)

**Comment by bshyong** [comment]
I have a feeling that this is related to some bugs in the build that is deployed to `gh-pages`. The pattern should show up as Radio Button. I will take a look at the build and see what the issue is
