### ISSUE TITLE
Reorganize PatternLab

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets.gov-patterns#25]
**Atoms**
Global
- colors
- content
  - fonts
  - headers
  - page copy
  - spacing
  - links (internal/external)
  - disclaimer text

Buttons
- standard
- action buttons

Dividers
Logos
- DSVA
- Vets.gov
- VA

Inputs
- types
  - text
  - textarea
  - checkbox
  - radio
  - dropdown
  - multiple select
  - search (inline input)
- states
  - success
  - error
  - disabled
  - required

List
- Bulleted
- Ordered

Loader
- React Loading

Navigation
- Tabs
- Subway nav
- Navigation Card

Misc

**Molecules**
Breadcrumbs (using links)
Form (using Inputs and Buttons)
- Field with Label
- Search Field
- Date of Birth

Misc
- Callout Boxes
- Piano Keys

**Organism**
Stacked Form

**Comment by bshyong** [comment]
@crwallace what is a stacked form? Is there an example somewhere I can use as a reference?

**Comment by crwallace** [comment]
@bshyong -- A form with stacked form elements. Like all of the pages on HCA are stacked forms
