### ISSUE TITLE
Feature audit: Secure Messaging

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#30]
## New patterns
**1. Two-tiered page headings** (similar to Prescriptions)
> <img width="583" alt="screen shot 2016-11-28 at 1 58 06 pm" src="https://cloud.githubusercontent.com/assets/4106356/20687792/bf47f4d0-b572-11e6-86c6-a67e3ecd1633.png">

**2. Alternate disabled button state**

Disabled state for primary and outline buttons:
> <img width="258" alt="screen shot 2016-11-28 at 2 16 59 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688381/6a44a44e-b575-11e6-8f00-0a7fc5e144b6.png">

Compared to USWDS default:
> <img width="139" alt="screen shot 2016-11-28 at 2 18 14 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688410/833ec4a2-b575-11e6-994d-206a9609d0ea.png">

**3. Icons as standalone links or paired with text links**
> <img width="200" alt="screen shot 2016-11-28 at 2 19 33 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688476/c6bf2604-b575-11e6-9ead-59c837a3ef2a.png"> <img width="200" alt="screen shot 2016-11-28 at 2 42 02 pm" src="https://cloud.githubusercontent.com/assets/4106356/20689192/e1a662a4-b578-11e6-90a2-b8d3d46eb183.png"> <img width="200" alt="screen shot 2016-11-28 at 3 14 18 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690071/67bf6102-b57d-11e6-8792-7c0e7a760077.png">

**4. Previous / next links in message lists**
> <img width="261" alt="screen shot 2016-11-28 at 2 36 44 pm" src="https://cloud.githubusercontent.com/assets/4106356/20689006/2bc0b228-b578-11e6-8dbc-d6e864cddb80.png">

**5. Advanced search**
> <img width="804" alt="screen shot 2016-11-28 at 2 39 16 pm" src="https://cloud.githubusercontent.com/assets/4106356/20689090/7a7c1e3e-b578-11e6-9629-fb6768c0b40c.png">

**6. Back links**
> <img width="215" alt="screen shot 2016-11-28 at 3 36 13 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690601/6fea8bce-b580-11e6-96dc-07bd21f912e0.png">

**Changing the back link to now be a button. Created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/200).**

**7. Navigation**
   - Desktop: sidebar
> <img width="235" alt="screen shot 2016-11-28 at 3 37 54 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690656/bd634274-b580-11e6-86d7-f5aaf9df83d8.png">

   - Mobile: link to overlay
> <img width="343" alt="screen shot 2016-11-28 at 3 38 08 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690660/c357f6f2-b580-11e6-8bab-57f8e87abf0a.png">

## Inconsistencies / bugs

1. Compose message - functional differences between desktop & mobile:
   - Trash button (desktop) vs. Cancel link (mobile) - do these do the same thing?

**@melwoodard Good question, I was thinking the cancel link would be if you decided you didn't want to compose a message or if you were editing a message you and wanted to cancel your changes without deleting the message itself. However, I do think we then need a delete link for mobile then for when you want to delete the message all together from the compose or edit draft view. I'm going to create an issue to add a delete button right aligned above the "Save a draft" button. Let me know if you think this doesn't make sense.**

**Issue created [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/192).** 

2. Pagination on message lists is missing on mobile

**This is being tracked [here]( https://github.com/department-of-veterans-affairs/messaging-fe/issues/174).**

3. Header for edit draft screen on mobile should not read "New message" since it's an existing draft

**Agreed, will change this to say "Edit draft" instead for drafts. An issue has been created [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/193).**

4. Are drafts able to be moved into folders? Got an error when attempted. If they aren't, the [move] dropdown shouldn't be shown on drafts

**Drafts should not be allowed to move into folders. I added an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/182).** 

5. Compose message - all fields are different lengths
> <img width="797" alt="screen shot 2016-11-28 at 2 01 44 pm" src="https://cloud.githubusercontent.com/assets/4106356/20687913/46965f12-b573-11e6-88a4-3a83c5c279f6.png">

**@melwoodard Agree that there should be a better lengths to these. What if we made it like this?** 
![image](https://cloud.githubusercontent.com/assets/103496/20731720/5a9acdea-b640-11e6-9923-9414c73b0a6f.png)
**Let me know what you think and I can create an issue.**

**Issue created [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/198).** 

6. Field labels should be regular weight, no colons
> <img width="302" alt="screen shot 2016-11-28 at 2 15 15 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688301/247fbd54-b575-11e6-80d2-94727cb1d1cd.png">

**Created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/183).** 

7. Placeholder text in fields - should this be a label instead?
> <img width="460" alt="screen shot 2016-11-28 at 2 20 40 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688509/edca85ae-b575-11e6-81b5-e982ea572302.png">

**Yeah, I think you're right. I think it might be a little confusing with the two labels "Subject line" and "Additional subject line", but I think it's better than having the placeholder disappear when you type. I created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/186).** 

8. Attachment [x] button should attach to the top right corner rather than bottom right
> <img width="391" alt="screen shot 2016-11-28 at 2 29 36 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688789/2fb7539c-b577-11e6-994a-036c6f8a7f3c.png">

**Agreed, created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/184).** 

9. Message lists are missing inline To / Subject Line labels on mobile
Inconsistent with established behavior for tables on mobile, but does it make sense as an outlier in this context? If so, at least look at typographical hierarchy improvements, can't tell which is the subject and which is the recipient
> <img width="318" alt="screen shot 2016-11-28 at 2 34 26 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688949/e59a764e-b577-11e6-9ab1-d126fd005e5c.png">

**I think this makes sense as an outlier here to not have the inline to/subject line but I think hierarchy improvements of definitely needed here. I think the to field should be bigger than the subject line and the subject line should be a lighter gray color. I have created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/190).** 

10. Advanced search date range - date fields should remain side-by-side at a fixed width on mobile instead of defaulting to 100% width
> <img width="391" alt="screen shot 2016-11-28 at 2 47 02 pm" src="https://cloud.githubusercontent.com/assets/4106356/20689310/9ed4409e-b579-11e6-9b30-2c39338a4135.png">

**Agreed, created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/187).** 

11. Duplicate subject line and delete button on drafts
> <img width="797" alt="screen_shot_2016-11-28_at_2_48_55_pm" src="https://cloud.githubusercontent.com/assets/4106356/20689361/e7dd1ae0-b579-11e6-9bd3-dbaed2bbb346.png">

**I think for when drafts are not attached to a thread we can remove the top subject line area which would delete the delete button and look like this:** 

![image](https://cloud.githubusercontent.com/assets/103496/20733154/e058a19a-b646-11e6-987e-40411391b709.png)

**but if it's a draft to a thread it would look like this:** 

![image](https://cloud.githubusercontent.com/assets/103496/20733511/b01763c0-b648-11e6-85e6-123f6bcb4a7a.png)

**@melwoodard would that be weird? Also I removed the delete at the top that would delete the message, I think at this view you should only be able to delete draft. Does that make sense?** 

**Issue created [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/199).** 

12. Folders list table is not mobile-friendly
> <img width="339" alt="screen shot 2016-11-28 at 2 58 39 pm" src="https://cloud.githubusercontent.com/assets/4106356/20689616/395cbb4a-b57b-11e6-8ba4-4f52df360979.png">

**For the folders in mobile we could stack it the way the Rx does mobile like so:** 
![image](https://cloud.githubusercontent.com/assets/103496/20733053/71d2afa4-b646-11e6-976f-7f7785894543.png)
**@melwoodard Do you think that it makes more sense for the folder name to be bold and no underline for both desktop and mobile to be more consistent with the way we do names in Rx?** 

**Issue created [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/194).** 

13. Overlay styles are non-standard - compare to prescriptions (right)
> <img width="200" alt="screen shot 2016-11-28 at 3 46 53 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690873/03a5443e-b582-11e6-9a63-4d16236bb016.png"> <img width="200" alt="screen shot 2016-11-28 at 3 50 49 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690947/7de632ee-b582-11e6-83a8-63dd68afa579.png"> <img width="200" alt="screen shot 2016-11-28 at 3 48 06 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690896/26bfb1de-b582-11e6-914b-26544fbadebd.png">

**@melwoodard I think if we change the blue text for the SM ones to match the black of the glossary header modals that would make the most sense. I don't think the SM ones need to have the blue bar:**

![image](https://cloud.githubusercontent.com/assets/103496/20844258/ce63b57c-b873-11e6-8f92-caf15d576d4c.png)

 **I don't know what we would put in there that makes the most sense or adds value. The question seems long to put in the blue bar. I think it could still be consistent to the glossary modal of Rx, just doesn't have a blue bar. Would that be ok with our design patterns?**

**Issue created [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/197).** 

14. Standardize icon + text link pairings to a blue _non-underlined_ icon + blue underlined text
   - Trash icon should never be standalone, should be paired with "delete" text
> <img width="200" alt="screen shot 2016-11-28 at 2 19 33 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688476/c6bf2604-b575-11e6-9ead-59c837a3ef2a.png"> <img width="200" alt="screen shot 2016-11-28 at 2 42 02 pm" src="https://cloud.githubusercontent.com/assets/4106356/20689192/e1a662a4-b578-11e6-90a2-b8d3d46eb183.png"> <img width="200" alt="screen shot 2016-11-28 at 3 14 18 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690071/67bf6102-b57d-11e6-8792-7c0e7a760077.png">

**Sounds good, created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/185).** 

## For discussion

1. Deleting folders - it's not clear whether deleting a folder also deletes the messages within it. Is that the case? If so, selecting delete should trigger an additional overlay to explain this and allow the user to confirm or cancel.

**@melwoodard @gnakm deleting a folder would also delete those messages and move them to the deleted folder. Is that right @U-DON? I think a modal here to make that message clear would be helpful. I can create an issue for this.** 

2. Compose button - is large size appropriate?
> <img width="227" alt="screen shot 2016-11-28 at 1 58 59 pm" src="https://cloud.githubusercontent.com/assets/4106356/20687822/e12b23d8-b572-11e6-8c86-cd7b4189d519.png">

**@melwoodard large as opposed to the regular size? We had Veterans say they couldn't find the compose button so we went with the bigger size.** 

3. Delete draft button is an icon only - should it be paired with text, or should it be a standard button, or both?
   - General issue of use of text links vs. buttons, echoed in [Prescriptions audit](https://github.com/department-of-veterans-affairs/vets.gov-designpattrns/issues/29)

**@melwoodard I think it should be icon and text like stated in 14 under "inconsistencies/bugs". /cc @gnakm** 

4. Flow for editing a draft takes 1 more step in mobile - why? I select the draft from a list, then see a page with the "edit draft" button that then takes me to edit mode. On desktop I go straight from the draft list to edit mode.
   - Flow for replying to a message has same additional step
> <img width="280" alt="screen shot 2016-11-28 at 2 08 20 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688110/3ad851e8-b574-11e6-874c-fd6459d391a0.png"> <img width="280" alt="screen shot 2016-11-28 at 2 08 37 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688115/3c63e43c-b574-11e6-8675-7c9ea542e815.png">

**@melwoodard at the time I thought that since editing a draft takes up the whole screen that it would be nice to see the message thread first and then click "Edit draft", but maybe edit draft doesn't need to take the whole screen and we add the thread to the top. I'll have to play with it to see what it would look like. /cc @gnakm** 

5. Icons in "things you should know" box - do these supplement the content? Are they necessary?
> <img width="316" alt="screen shot 2016-11-28 at 2 21 57 pm" src="https://cloud.githubusercontent.com/assets/4106356/20688565/27db54d0-b576-11e6-97f9-17309bab9856.png">

**@melwoodard I thought that the icons were a nice way to break up the block of text and looked a little more friendly. /cc @gnakm** 

6. Previous / next links in inbox / drafts list
Should this align with the default pagination style?
> <img width="261" alt="screen shot 2016-11-28 at 2 36 44 pm" src="https://cloud.githubusercontent.com/assets/4106356/20689006/2bc0b228-b578-11e6-8dbc-d6e864cddb80.png">

**The default pagination doesn't have a pattern for showing how many items are on the pages just the number of pages and are usually at the bottom. I think for SM this style works better, but am open to hearing thoughts to persuade me otherwise or to change it to be closer to the default pagination. /cc @melwoodard @gnakm** 

7. Existing messages (received, drafts) have a different heading font style, location, and chrome compared to message lists and new messages. How can these line up better?
- Message list:
> <img width="1036" alt="screen shot 2016-11-28 at 3 35 18 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690694/f00157ca-b580-11e6-8912-0ed5ca04a8c6.png">
- New message:
> <img width="1044" alt="screen shot 2016-11-28 at 3 40 19 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690705/ff65569e-b580-11e6-8d41-f806fe5e7468.png">
- Existing message:
> <img width="1034" alt="screen shot 2016-11-28 at 3 33 54 pm" src="https://cloud.githubusercontent.com/assets/4106356/20690697/f313b480-b580-11e6-94bb-d57193318ab8.png">

**@melwoodard @gnakm we could leave the name of the folder above the existing messages. Would that make it more consistent?** 

8. Success message alerts surface a link to view a message / folder the user just acted on. Would a button better serve this purpose?
<img width="1077" alt="screen shot 2016-11-28 at 3 55 03 pm" src="https://cloud.githubusercontent.com/assets/4106356/20691066/449286d6-b583-11e6-9ea2-4f54ec0ca0d3.png">

**@melwoodard @gnakm I think for this one the link is better since "View message" is not necessarily the next action we want them to take but the link is there for the Veteran to easily access it if they happen to want to see that message.**

**Comment by melwoodard** [comment]
@gnakm @angel I'd love to get your eyes and input on this audit. Not everything in the Inconsistencies / For discussion categories needs an answer right away -- but for any that have a straightforward solution, please go ahead and create front-end issues for them.

**Comment by ahelkit** [comment]
@melwoodard @gnakm added my thoughts for the items under "For discussion" inline above. I'll look at the inconsistencies and bugs tomorrow. Thanks for doing this Mel!

**Comment by melwoodard** [comment]
@angel thanks for the feedback! My thoughts:

1. Deleting folder - makes sense to me to have a modal if this is the case

2. Large compose button - makes sense if there were issues finding it

3. Delete button paired with text - agreed

4. Extra step for draft editing - I think the initial button that leads to a separate screen can make sense for replying to a thread, but for navigating to the drafts folder and selecting a draft to edit, it feels like that extra step isn't needed. 

5. Icons - fine with leaving as-is, just a thought on our broader icon conversation

6. Pagination - I agree showing the number of items makes sense, it's the button style that feels more like an outlier. I'd like to see how this looks with prev/next styled as text links, or keeping the buttons but aligning them more to our standard button style - rounded corners, use of blue, etc.

   Another thought - it doesn't appear that these buttons have a disabled state. 

7. Headings - not sure I follow, isn't the name of the folder already above the existing message? I see two issues - (1) the heading styles are different - bold vs. regular, (2) all the things that make up the top portion of the main column seem to move around / change hierarchy from screen to screen. 2 is a little harder to solve, maybe we can put it on the radar for later exploration.

8. Success alerts - makes sense to me

Found one more thing - the pagination is missing on mobile.

**Comment by U-DON** [comment]
Regarding the deleting folder point, apparently the API prevents deletion of a folder that has messages within it. It just sends back an error in that case, so we show an error alert as a result.

**Comment by ahelkit** [comment]
@melwoodard 

4. Extra step for draft editing - I think that works for drafts that are not attached to a thread. For those with a thread, it seems a little trickier. Would this work? 
![image](https://cloud.githubusercontent.com/assets/103496/20731611/f4488686-b63f-11e6-9d3a-a2ad42ff825c.png)

6. Pagination - will try this out. Right now, the disabled state should have the buttons a lighter gray. The color different might not be as noticeable though cause the lightest gray we could go with it still passing is not very light. 

7. Headings - Hmm, I thought you meant how existing messages there's no bold title like "New message" or "Inbox", so I was saying that we could add that title back in. So a Veteran was reading their messages like the existing messages view it we could add the title "Inbox". Does that make sense? Or for now would bolding the subject line make sense? 
- 2. for later exploration sounds good. 

Pagination missing in mobile is captured under Inconsistencies 2. Let me know if there's something different. 

Thanks!

**Comment by ahelkit** [comment]
@U-DON I didn't know that. So right now users can't delete any folders with messages? So that button in the manage folders shouldn't be there for folders that don't have messages right?

**Comment by U-DON** [comment]
@angel You mean they shouldn't have buttons for folders that do have messages? Right now, clicking 'Delete' on a folder in that page for a folder that has a non-zero message count will raise an error.

**Comment by melwoodard** [comment]
I think keeping the buttons and showing the error message makes sense, otherwise a user won't necessarily know why some folders have a button and others don't. Ultimately it would be great to add functionality to delete a folder regardless of whether it contains messages, and possibly give the choice to keep the messages or delete them.

**Comment by ahelkit** [comment]
@U-DON whoops yeah that's what I meant, but I think @melwoodard is right. Let's keep it in there for now but have the error message.

**Comment by ahelkit** [comment]
@melwoodard ok, I have gone through all the inconsistencies/bugs. I have left some comments and questions. Let me know what you think and I can create issues for the remaining ones that don't have any right now. Thanks!

**Comment by melwoodard** [comment]
Thanks for adding issues. Here's my feedback on a few, the rest of the changes are great:

1 - Delete button right aligned above the "Save a draft" button - **makes sense to me!**

5 - Message field lengths - the "to" field seems like a tight squeeze for the content. Is it too goofy to make it 100% width? Otherwise it seems like text not fitting will be a pretty common case here.

11 - Duplicate subject line and delete button on drafts - I think this makes sense, and it checks out with how gmail handles contextual actions depending on how you accessed the draft.

12 - Folders not responsive - agreed on responsive behavior to convert to a stacked list

13 - Modals - it seems like the blue header bar is too prominent given that it isn't always applicable with the content. Sounds like this needs some design thought across the board, I'll open a separate issue to address

**Comment by ahelkit** [comment]
@melwoodard thanks for the feedback. I'll add issues for the ones mentioned above.

5 - It looks a little goofy, but it could work. Probably better to have it goofy but show the full name. What do you think?
![image](https://cloud.githubusercontent.com/assets/103496/20779728/2ad84f42-b72b-11e6-949a-26f0aab610a1.png)

13 - Modals - I'm going to change the bold text to the dark gray for now since it's not a link and we can change it to whatever we decide across the board later.

**Comment by melwoodard** [comment]
I think the longer field works ok, and it'll be much more practical. Sounds good on the modal text color too. Thanks!

**Comment by ahelkit** [comment]
@melwoodard Thanks! I've created issues for those.

For the pagination would this be more consistent? 

![image](https://cloud.githubusercontent.com/assets/103496/20851582/33e18cea-b896-11e6-962c-e8bf771ff2ff.png)

![image](https://cloud.githubusercontent.com/assets/103496/20851661/9fda643a-b896-11e6-9795-7f09f6078170.png)

**Comment by melwoodard** [comment]
@angel definitely more consistent. How do you feel about this approach, do you think the pagination links still feel actionable enough?

**Comment by ahelkit** [comment]
@melwoodard I think so, but I'm not sure. Also do you think it will be ok for the move button to still look the way it does? It was kind of nice to have similar styling for the two, but I don't think it makes sense for the move button to be link. What do you think? 

![image](https://cloud.githubusercontent.com/assets/103496/20941145/1014d882-bbaa-11e6-9d90-7f2e42267027.png)

**Comment by melwoodard** [comment]
I think you're right - 'move' is a dropdown, so it makes sense to look that way. To play devil's advocate (admittedly against myself), what if the back link style was changed to the boxy format, so that all links in that row are boxes?

**Comment by ahelkit** [comment]
@melwoodard I mocked it up below. I thought I would dislike it more, but it's not so bad. But I also like when it's just the back to inbox as a link just to visual break up that task from the other tasks and might help when scanning the actions a Veteran can take. 

![image](https://cloud.githubusercontent.com/assets/103496/20988133/4bb69d00-bc84-11e6-97bb-0b79aebeaeab.png)

**Comment by melwoodard** [comment]
I see that to an extent, though I'd argue that Back isn't much different from Previous / Next - it's all navigation. Overall I think the same style all the way across creates a much more solid "action bar", and it seems like all buttons is less problematic than all links.

If we go with buttons all the way, the back link text should also probably be simplified to just "back" (otherwise a folder name could make it very long). Taking cues from gmail (except with words instead of icons):

![image](https://cloud.githubusercontent.com/assets/4106356/20988223/aacc4524-bc84-11e6-835b-c77e672c06b3.png)

**Comment by ahelkit** [comment]
@melwoodard True. Sounds good, should we do back and an icon? Or just back?

**Comment by melwoodard** [comment]
I like [ < Back ], the icon helps quickly identify what the button does.

**Comment by ahelkit** [comment]
@melwoodard agreed. I think we should go with the buttons all the way. I made created an issue [here](https://github.com/department-of-veterans-affairs/messaging-fe/issues/200). I think that covers all the issues! Let me know if I missed anything. Thanks!
