### ISSUE TITLE
Consolidate modal styles

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#35]
The original design with dark blue heading (right) is causing issue when certain modals don't have a need for a two-tiered heading. Need to explore options to present a more consistent visual design that's flexible to content variations.

<img width="630" alt="screen shot 2016-11-30 at 4 48 52 pm" src="https://cloud.githubusercontent.com/assets/4106356/20777606/e8fa3f44-b71c-11e6-8715-35fc948036df.png">

**Comment by cweber** [comment]
Education also has this modal which was based on the prescription modal on the right, but needed a way to express to clear choices. (There are some padding issues in these screenshots that have issues submitted about them.)

Desktop
![screen shot 2016-12-02 at 11 48 16 am](https://cloud.githubusercontent.com/assets/417657/20842387/6c444692-b885-11e6-8cbd-e9370e0345d3.png)

Mobile
![screen shot 2016-12-02 at 11 49 21 am](https://cloud.githubusercontent.com/assets/417657/20842391/703f7c8a-b885-11e6-861d-b55d08b60d2d.png)

**Comment by cweber** [comment]
Also worth looking at the crisis line and search modals.

**Comment by melwoodard** [comment]
Thanks @cweber! What triggers that modal on the Edu apply page? I'm having trouble finding it.

Documenting current state of VCL and search modals here as well:

VCL desktop:
<img width="353" alt="your_vets_gov_account__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20850511/6437de36-b890-11e6-82ad-fc387643b964.png">

VCL mobile:
<img width="399" alt="your_vets_gov_account__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20850528/7d4fa638-b890-11e6-8988-9cda7699d95d.png">

Search mobile:
<img width="398" alt="your_vets_gov_account__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20850550/972a6156-b890-11e6-90e2-801d69766a65.png">

**Comment by cweber** [comment]
Yeah, it's weird. It will only show up if linked to. (Mostly for external redirects.)

https://dev.vets.gov/education/apply-for-education-benefits/#modal

**Comment by melwoodard** [comment]
Ah, I see. Smart!

**Comment by melwoodard** [comment]
Handled in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1047
