### ISSUE TITLE
Type style for accordions seems out of sync with Vet.gov type colors

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets.gov-patterns#36]
The type style for accordions, as used in form review for edu-benefits, is pulled directly from US WDS, but seems out of sync with vets.gov type choices. Specifically, it's black. (really, dark grey, but with not blue hue to it.)

**Comment by melwoodard** [comment]
Thanks for pointing this out - we actually have a pretty inconsistent mix of dark grey and dark blue happening in our headings and need to standardize on one color.
