### ISSUE TITLE
Feature Audit: Application Forms (Edu / HCA)

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#37]
## New patterns

1. Sidebar process list converts to a step indicator in the heading at smallest breakpoint

   > <img width="316" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20844527/18422f1a-b875-11e6-91a3-7e88fd6cd6d8.png">

2. Progressive disclosure - field input/selection reveals additional information and/or fields

   Reveal information:

   > <img width="530" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20844991/847ff624-b877-11e6-81cc-f3c103426238.png">

   > <img width="530" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20844955/51a5d8cc-b877-11e6-967b-9795a44d5cfc.png">
   
   Reveal additional fields:

   > <img width="646" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20845528/7026f620-b87a-11e6-80d2-0b10c686c0e6.png">

3. Opposite of progressive disclosure - field input/selection hides irrelevant fields

   > <img width="300" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20846685/a9fdc464-b87f-11e6-8875-575330bfc6fa.png">

   > <img width="300" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20846730/cd6b47e6-b87f-11e6-8bac-8d18c1a37484.png">

## Inconsistencies / bugs

1. Button widths don't follow the default rule. Width should be auto @ medium/large breakpoints, and 100% at small; instead the width is being set as a fixed number of columns.

   > <img width="271" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20844403/6e76ee1c-b874-11e6-8fb8-e487d212c6d1.png"> 

   > <img width="319" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20844337/22df311c-b874-11e6-895b-b4bc3531b4df.png">

2. Button font weights should default to 700, not 500

   > <img width="372" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20845916/1d4c7090-b87c-11e6-8b37-3248935059a1.png">

3. Inconsistency in text color / weight in review boxes - dark blue vs. grey, bold vs. regular

   > <img width="540" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20845827/adb95aea-b87b-11e6-837a-c2dbbf9e10d2.png">

   > <img width="536" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20846432/6ad0f000-b87e-11e6-9945-b05694f7f321.png">

   > <img width="532" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20847408/c8e8efae-b882-11e6-850d-1dbd3defebee.png">

4. Dropdown fields with long inputs need "..." truncation

   > <img width="497" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20846538/f9ef289c-b87e-11e6-8e19-ee716c579fb3.png">

5. Inconsistency in Edit button styles - font weight, icon use

   > <img width="590" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20847446/f3c2ffa8-b882-11e6-9ce5-52cfab6a4366.png">

## For discussion

1. Page headings are not consistently `h1` - this appears to be primarily for sizing reasons, but is not as friendly to screen readers
   - Intro screen heading is currently `h3`
   - Other screen headings are `legend` styled as an `h4` on larger breakpoints; `h4` at smallest breakpoint

2. Can we get date fields all on a single line at smaller phone screen widths? (320px iphone)

   > <img width="317" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20845604/b4fa93f6-b87a-11e6-9eca-c5a5ad1b917e.png">

3. Outline style buttons on grey backgrounds have inconsistent fill colors - white in Edu, transparent in Rx
   
   Edu:
   > <img width="540" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20845827/adb95aea-b87b-11e6-837a-c2dbbf9e10d2.png">

   Rx:

   > <img width="280" src="https://cloud.githubusercontent.com/assets/4106356/20846038/9a07b1e4-b87c-11e6-977f-baabc3a2bc30.png">

4. While having the primary action in the lower left passes the straw test better, it's pretty typical for the primary action to be in the lower right (like the 'comment' button in this very issue) - I almost selected remove because of that convention. What if the 'remove' action was a text link to further deemphasize it and prevent accidental selection?

   > <img width="295" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20846294/dbacf5f4-b87d-11e6-8f72-f4c2dcb2195b.png">

5. Labels for benefits eligibility step are inconsistent - isn't the name of the highlighted bullet within the step supposed to be the same as the legend name on the right?

   > <img width="566" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20847028/2546fc48-b881-11e6-8ff8-99f994e106a6.png">

6. Summary views of entries like Military History, Education History surface different levels of information depending on whether they're at the step level or review level. Can these be more consistent, and if so - which is the right level of detail?
   
   Military History step:
   > <img width="535" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20847291/46427cd2-b882-11e6-81d8-e42d89f715a2.png">

   Review step:
   > <img width="560" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20847311/59c8bef6-b882-11e6-880a-d451a862c434.png">

7. Review step - field label styles

   Similar conversation happening in the other audits on styling for labels that sit inline with their corresponding values? 

   For Claims, Rx and FL we decided to standardize on bold/dark grey for labels, regular/dark grey for values. 
   
   > <img width="553" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20847727/22aaa7ac-b884-11e6-8279-812bfe7873a4.png">

8. Accordion component on 'Claim Received' screen breaks standard style - container padding, +/- icon style/font, background color for heading vs. body. Is there any reason it shouldn't use the standard style?

   > <img width="628" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20848094/7b603b40-b885-11e6-9ec4-7ac9e9a71801.png">

   Vs.
   > <img width="629" alt="apply_for_education_benefits__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20848129/9804a268-b885-11e6-93e9-9080f0ca8d7c.png">

**Comment by melwoodard** [comment]
@goldenmeanie @cweber I'd love to get your eyes and input on this audit. Not everything in the Inconsistencies / For discussion categories needs an answer right away -- but for any that have a straightforward solution, please go ahead and create front-end issues for them.

**Comment by goldenmeanie** [comment]
Fresh eyes!

_embarassed_

**Comment by cweber** [comment]
**Inconsistencies/Bugs**

1. Will submit issue.

2. Will submit issue

3. Will submit issue and normalize to grey. (Blue was a holdover pattern from HCA review screen that we didn't change because maybe it was intentional? :-/ )

4. Will submit issue

5. Will submit issue (Normalize towards 700 weight, no icon.)


**For Discussion**

1. I have a lot of feels about this. All of them are in line with your feels. The HTML structure for these forms is NOT cool, but it feels baked into the CSS (A lot of it is baked into common components.). e.g Our playbook claims that H1 and H2 are reserved for logo and the breadcrumb.

Will create an issue.

2. Yes. Will create an issue.

3. Yep. Will create an issue.

4.  Agreed this is confusing, we'll try changing the ghost button as text before we start changing positioning.

5. Thought we had all of those headers fixed. Will create an issue.

6. We think it's fine if it's different. In the first version we space matters more and they will have just filled out that content. We are also anticipating some people filling out many records. In the review state, seeing all of the details matters.

7. Agreed that the blue labels is weird. It's a holdover from HCA. Was curious to see if it would show up elsewhere as the norm.

**Bold** vs regular makes sense, though I would argue for regular vs **bold**. I'd rather highlight the values. Though I wonder if that feels more important in our context where some of our labels are several lines long and the answer is just a simple yes/no/date.

8. Will create issue.

**Comment by melwoodard** [comment]
Thanks! My feedback -

- Headings - yeah...this one's tough. If you want to file an issue it'd be great to collaborate with front-end folks to figure out how to improve the overall HTML structure, and also find a solution for cases where H1 doesn't feel right visually, but needs to be used for hierarchical reasons.
- Level of detail in summary cards - works for me, makes sense since some of them have a good number of fields
- Styling the review screen as '**bold label** / regular value' makes sense to me too, since the context is reviewing _my_ input to make sure it's correct, not identifying types of information the VA is providing to me
