### ISSUE TITLE
Feature Audit: Claim Status

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#38]
## New patterns

1. Tabbed pages (also in Prescriptions and Facility Locator mobile)

   > <img width="667" alt="status_-_your_disability_compensation_claim" src="https://cloud.githubusercontent.com/assets/4106356/20978865/6330962c-bc5f-11e6-87cf-47779dfc1e3b.png">

2. Process list with accordion functionality

   > <img width="666" alt="status_-_your_disability_compensation_claim" src="https://cloud.githubusercontent.com/assets/4106356/20978880/73553800-bc5f-11e6-8b8f-140ca1504c28.png">

3. Form inputs within definition cards

   > <img width="539" alt="screenshot-staging_vets_gov-2016-12-07-09-47-13_png" src="https://cloud.githubusercontent.com/assets/4106356/20981632/66476c5e-bc6a-11e6-8b01-532244592301.png">

## Inconsistencies / bugs

1. Font weight of labels/values - other apps are standardizing to format as **bold label:** regular value

   > <img width="668" alt="track_claims__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20978683/a4f1d16c-bc5e-11e6-93d1-2d5f7d35e4ae.png">

2. Underlined page section headings should be modified to an H2 for better hierarchy/screenreading capabilities - see [this related issue](https://github.com/department-of-veterans-affairs/vets-website/issues/4175) for Prescriptions

   > <img width="669" alt="files_-_your_disability_compensation_claim" src="https://cloud.githubusercontent.com/assets/4106356/20979266/224c8420-bc61-11e6-8c93-c4e60f00505e.png">

3. White button backgrounds on grey cards - elsewhere these are being standardized to transparent backgrounds

   Claim status:
   > <img width="667" alt="files_-_your_disability_compensation_claim" src="https://cloud.githubusercontent.com/assets/4106356/20979133/69ab98ac-bc60-11e6-8f8a-fc1901266249.png">

   Prescriptions:
   > <img width="507" alt="refill_your_prescriptions__vets_gov" src="https://cloud.githubusercontent.com/assets/4106356/20979181/a1ee54b6-bc60-11e6-90ae-04f7fce3fd90.png">

4. File upload - filename containers are a too-narrow fixed width; should be allowed to extend to the left edge of the 'remove' button

   > <img width="664" alt="additional_evidence" src="https://cloud.githubusercontent.com/assets/4106356/20979713/bc7ebada-bc62-11e6-9bf7-5d2013445d6d.png">

5. Buttons in alerts, cards, etc. should stay locked to the top of their containers

   > <img width="300" alt="screenshot-staging_vets_gov-2016-12-07-09-47-28_png" src="https://cloud.githubusercontent.com/assets/4106356/20981712/9ab807f0-bc6a-11e6-92a1-8e8d9f6561b0.png">

6. Remove blue background on 'success' alert close button

   > <img width="664" alt="files_-_your_disability_compensation_claim" src="https://cloud.githubusercontent.com/assets/4106356/20979911/5d9a956a-bc63-11e6-9c77-af46c34a8bfb.png">

## For discussion

1. Hierarchy / labels for submitted files - we previously decided on the version on the left, but it holds greater inconsistency now with the way we're beginning to standardize on bold labels (see # 1 in inconsistencies/bugs section).

   > <img width="841" alt="screen_shot_2016-11-04_at_4_00_59_pm_png__2058x1018_" src="https://cloud.githubusercontent.com/assets/4106356/20981299/ef5623a2-bc68-11e6-8e80-6be5d8944360.png">

2. Upload screen - should the submit button override the default to 100% width on mobile so that the submit & cancel buttons can remain side by side? With cancel floating below it's easy to miss as an option. This also lines up with other two-option layouts on mobile.

   Claim status:
   > <img width="322" alt="screenshot-staging_vets_gov-2016-12-07-09-47-28_png" src="https://cloud.githubusercontent.com/assets/4106356/20981935/5298899e-bc6b-11e6-85c0-82163b5c3f5e.png">

   Prescriptions:
   > <img width="242" alt="screenshot-staging_vets_gov-2016-11-28-13-52-44_png" src="https://cloud.githubusercontent.com/assets/4106356/20981951/6f456760-bc6b-11e6-9219-1edd7925a546.png"> <img width="303" alt="screenshot-staging_vets_gov-2016-11-28-13-54-31_png" src="https://cloud.githubusercontent.com/assets/4106356/20981982/8a424d9e-bc6b-11e6-9568-3b9abe6b02f8.png">

**Comment by melwoodard** [comment]
@suzchap I'd love to get your eyes and input on this audit. Not everything in the Inconsistencies / For discussion categories needs an answer right away -- but for any that have a straightforward solution, please go ahead and create front-end issues for them. I did my best to approach this with fresh eyes, but there's always a chance I missed something :)

**Comment by suzchap** [comment]
@melwoodard This is great!

I'll submit tickets for all the "inconsistencies" items.

Re: "For Discussion" items...

1) Sure, we can go with the option on the right
2) Maybe - if it all fits on the same line. If it stays a link, it might fit but if we make it a button like the confirm refill, it doesn't look like it will. But I'm happy to defer to you on this one.

**Comment by suzchap** [comment]
One note about making the buttons transparent... This button is also used on the yellow background. Going transparent on yellow passes WCAG AA and WCAG AAA but is probably borderline. VA is moving to a higher level of compliance in the future so we may have to reevaluate this later.

![image](https://cloud.githubusercontent.com/assets/11219417/21014815/65531500-bd2d-11e6-96bc-fe3a8e6671a8.png)

**Comment by suzchap** [comment]
And FYI, all but "for discussion" # 2 are now requested to devs via https://github.com/department-of-veterans-affairs/sunsets-team/issues/261

**Comment by melwoodard** [comment]
Thanks @suzchap! Good point on for discussion # 2. I think cancel should stay a link, but agreed that it depends on whether they fit on one line. Ideally the layout should be side-by-side until the viewport is too small for them to fit on one line, then it would break to the current two-line layout.

There's also some extra space between these, reducing that might help keep them on the same line on all but the smallest screen size

   > <img width="490" alt="screenshot-staging_vets_gov-2016-12-07-09-43-57_png" src="https://cloud.githubusercontent.com/assets/4106356/21017781/6ae99c0e-bd1f-11e6-820e-8b42c9396265.png">

Re: transparent buttons, I think slightly darkening the color for the outline button will help us meet 508. It actually looks like both the outline and solid blue buttons are failing AAA even on a white background. I'll log an issue for that change.

**Comment by suzchap** [comment]
@melwoodard cool. So I'll add a ticket for discussion # 2. Thanks!

**Comment by suzchap** [comment]
@melwoodard FYI, I do believe all the resulting sunset tasks have now been completed.
