### ISSUE TITLE
Unify date inputs

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets.gov-patterns#43]
- Secure messaging uses a date picker, which has a rather large JavaScript library as a dependency.
- Disability benefits uses a different, three-part date input. 

### Tasks

- Decide which form date inputs will use
- Decide whether we'll use browser input controls

**Comment by akainic** [comment]
This will likely affect HCA and education as well. We're having a separate conversation about date inputs on our teams here: https://github.com/department-of-veterans-affairs/vets-website/issues/3080. Perhaps we can have a broader conversation across teams? @cweber and @goldenmeanie will likely be interested in this conversation as well.

**Comment by goldenmeanie** [comment]
Big difference in utility when dealing with recent or near future dates vs those in the past.
